     
version: '2' 
volumes:
  peer0.Captain.tracemine.com:
  peer1.Captain.tracemine.com:
networks:
    traceminev1:
services:
  ca.Captain.tracemine.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.Captain.tracemine.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Captain.tracemine.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Captain.tracemine.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b traceminev1Captain:passw0rd'
    volumes:
      - ./crypto-config/Captain.tracemine.com/ca:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.Captain.tracemine.com
    networks:
      - traceminev1
    
  peer0.Captain.tracemine.com:
    container_name: peer0.Captain.tracemine.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_traceminev1
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.Captain.tracemine.com
      - CORE_PEER_ADDRESS=peer0.Captain.tracemine.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Captain.tracemine.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Captain.tracemine.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Captain.tracemine.com:7051
      - CORE_PEER_LOCALMSPID=CaptainMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch.peer0.Captain.tracemine.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=traceminev1Captain
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passw0rd
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    volumes:
      - /var/run/:/host/var/run/
      - .crypto-config/Captain.tracemine.com/peers/peer1.Captain.tracemine.com/msp:/etc/hyperledger/fabric/msp
      - .crypto-config/Captain.tracemine.com/peers/peer1.Captain.tracemine.com/tls:/etc/hyperledger/fabric/tls
      - peer0.Captain.tracemine.com:/var/hyperledger/production
    networks:
      - traceminev1

  couch.peer0.Captain.tracemine.com:
    container_name: couch.peer0.Captain.tracemine.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=traceminev1Captain
      - COUCHDB_PASSWORD=passw0rd
    ports:
      - 5984:5984
    networks:
      - traceminev1
    
  peer1.Captain.tracemine.com:
    container_name: peer1.Captain.tracemine.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_traceminev1
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.Captain.tracemine.com
      - CORE_PEER_ADDRESS=peer1.Captain.tracemine.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.Captain.tracemine.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Captain.tracemine.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Captain.tracemine.com:7051
      - CORE_PEER_LOCALMSPID=CaptainMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch.peer1.Captain.tracemine.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=traceminev1Captain
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passw0rd
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:7051
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/Captain.tracemine.com/peers/peer1.Captain.tracemine.com/msp:/etc/hyperledger/fabric/msp
      - ./ crypto-config/Captain.tracemine.com/peers/peer1.Captain.tracemine.com/tls:/etc/hyperledger/fabric/tls
      - peer1.Captain.tracemine.com:/var/hyperledger/production
    networks:
      - traceminev1

  couch.peer1.Captain.tracemine.com:
    container_name: couch.peer1.Captain.tracemine.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=traceminev1Captain
      - COUCHDB_PASSWORD=passw0rd
    ports:
      - 6984:5984
    networks:
      - traceminev1
    
  cli-Captain:
    container_name: cli-Captain
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.Captain.tracemine.com:7051
      - CORE_PEER_LOCALMSPID=CaptainMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Captain.tracemine.com/peers/peer0.Captain.tracemine.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations//peer0.Captain.tracemine.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Captain.tracemine.com/peers/peer0.Captain.tracemine.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Captain.tracemine.com/users/Admin@Captain.tracemine.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./cli-scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel
      - ./orderer-tls:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/orderer/tls
    depends_on:
      - peer0.Captain.tracemine.com
      - peer1.Captain.tracemine.com
    networks:
      - traceminev1
